name: CI-HelloWorld

on: #trigger
  push:
    branches:
      - branch-name
  workflow_dispatch: #manual run

jobs:
  with-checkout-job:
    name: With Checkout
    runs-on: 'ubuntu-latest'
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Install tree & run
        run: |
          sudo apt-get install -y tree
          tree .
      - name: Install dependencies
        run: |
          sudo apt-get install -y python3 python3-pip
      - name: Build package
        run: |
          pip install --uprade build
          python -m build
          tree .
    #  - name: Artifact creation
      #  run: |
       #   rm dist/


