name: CI-HelloWorld

on: #trigger
  push:
    branches:
      - branch-name
  workflow_dispatch: #manual run

jobs:

  hello-worls-job: #name of job
    name: Hello World
    runs-on: 'ubuntu-latest'
    steps:
      - name: Run echo
        run: | #run multiple commandsc
          echo "Hello world.!"

      - name: Run ls
        run: |
          ls -la
